name: Run Tests

on:
  push:
    branches:
      - main

jobs:
  test:
    runs-on: macos-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Xcode
      uses: apple/setup-xcode@v2  # Corrected repository name
      with:
        xcode-version: '15'

    - name: Install dependencies
      run: |
        xcodebuild -resolvePackageDependencies
        swift package generate-xcodeproj

    - name: Build and test
      run: xcodebuild test -scheme ChimpTest -destination 'platform=iOS Simulator,name=iPhone 13'
